# Generated by Django 2.2.6 on 2019-10-16 00:53

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listName', models.CharField(max_length=50)),
                ('listTag', models.CharField(max_length=50)),
                ('listDesc', models.CharField(max_length=250)),
                ('isPaid', models.BooleanField(default=True)),
                ('listLocation', models.CharField(max_length=100)),
                ('isOpen', models.BooleanField(default=True)),
                ('listLongDesc', models.TextField()),
                ('listOrgID', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgName', models.CharField(max_length=50)),
                ('orgLocation', models.CharField(max_length=100)),
                ('orgListings', django_mysql.models.JSONField(default=dict)),
                ('orgDesc', models.CharField(max_length=300)),
                ('orgIndustry', models.CharField(max_length=100)),
                ('authToken', models.CharField(default='', max_length=100)),
                ('orgPassword', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('dateOfBirth', models.CharField(max_length=50)),
                ('authToken', models.CharField(max_length=100)),
                ('userMajor', models.CharField(max_length=100)),
                ('userGPA', models.CharField(max_length=10)),
                ('userDegree', models.CharField(max_length=100)),
                ('userPassword', models.CharField(max_length=100)),
                ('userPitch', models.CharField(max_length=300)),
                ('extraCurriculars', django_mysql.models.JSONField(default=dict)),
                ('userBookmarks', django_mysql.models.JSONField(default=dict)),
            ],
        ),
    ]
