# Generated by Django 2.2.6 on 2019-10-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('dateOfBirth', models.CharField(max_length=50)),
                ('authToken', models.CharField(max_length=100)),
                ('userMajor', models.CharField(max_length=100)),
                ('userGPA', models.CharField(max_length=10)),
                ('userDegree', models.CharField(max_length=100)),
                ('userPassword', models.CharField(max_length=100)),
                ('userPitch', models.CharField(max_length=300)),
            ],
        ),
    ]
