# Generated by Django 2.2.6 on 2019-10-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgName', models.CharField(max_length=50)),
                ('orgLocation', models.CharField(max_length=100)),
                ('orgDesc', models.CharField(max_length=300)),
                ('orgIndustry', models.CharField(max_length=100)),
            ],
        ),
    ]
