# Generated by Django 2.2.6 on 2019-10-26 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20191024_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='listTag',
            new_name='listCategory',
        ),
    ]
