# Generated by Django 2.2.6 on 2019-10-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_startup'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='authToken',
            field=models.CharField(default='qwertyuiop', max_length=100),
        ),
        migrations.AddField(
            model_name='startup',
            name='orgPassword',
            field=models.CharField(default='root', max_length=100),
        ),
    ]
