# Generated by Django 2.2.6 on 2019-11-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20191026_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
