# Generated by Django 2.2.6 on 2019-10-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listOrgID',
            field=models.CharField(default='', max_length=100),
        ),
    ]
