# Generated by Django 2.2.6 on 2019-11-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_remove_customuser_authtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userGradYear',
            field=models.CharField(default='2023', max_length=4),
        ),
    ]
