# Generated by Django 2.2.6 on 2019-11-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_customuser_usergradyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userGradYear',
            field=models.IntegerField(default=2023, max_length=4),
        ),
    ]
