# Generated by Django 2.2.6 on 2019-11-16 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_auto_20191116_1938'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthUser',
        ),
    ]
