# Generated by Django 2.2.6 on 2019-11-16 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_delete_authuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='authToken',
        ),
    ]
