# Generated by Django 2.2.6 on 2019-11-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_remove_startup_authtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='extraCurriculars',
            field=models.CharField(default='', max_length=60),
        ),
    ]
