# Generated by Django 2.1.14 on 2019-11-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_auto_20191116_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='extraCurriculars',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listDeadline',
            field=models.CharField(default='2019-12-28', max_length=10),
        ),
    ]
