# Generated by Django 2.1.14 on 2019-11-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_auto_20191128_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='externalLink',
            field=models.CharField(default='', max_length=100),
        ),
    ]
